version: '3.8'

services:
  bot:
    image: fordibot
    container_name: fordibot
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
    build:
      dockerfile: docker/Dockerfile
      context: ../
